<?php
  $path_fonts = CMSHelper::getAssetPath('/assets/fonts');
  $path_images = CMSHelper::getAssetPath('/assets/images');
?>
<style type="text/css">
/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on January 5, 2018 */

@font-face {
    font-family: 'cormorantgaramond';
    src: url('{{ $path_fonts }}/cormorantgaramond-regular-webfont.woff2') format('woff2'),
         url('{{ $path_fonts }}/cormorantgaramond-regular-webfont.woff') format('woff'),
         url('{{ $path_fonts }}/cormorantgaramond-regular-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
@font-face {
  font-family: 'cormorantgaramond_medium';
  src: url('{{ $path_fonts }}/cormorantgaramond-medium-webfont.woff2') format('woff2'),
  url('{{ $path_fonts }}/cormorantgaramond-medium-webfont.woff') format('woff'),
  url('{{ $path_fonts }}/cormorantgaramond-medium-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
@font-face {
  font-family: 'cormorantgaramond_semibold';
  src: url('{{ $path_fonts }}/cormorantgaramond-semibold-webfont.woff2') format('woff2'),
  url('{{ $path_fonts }}/cormorantgaramond-semibold-webfont.woff') format('woff'),
  url('{{ $path_fonts }}/cormorantgaramond-semibold-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
@font-face {
  font-family: 'cormorantgaramond_bold';
  src: url('{{ $path_fonts }}/cormorantgaramond-bold-webfont.woff2') format('woff2'),
  url('{{ $path_fonts }}/cormorantgaramond-bold-webfont.woff') format('woff'),
  url('{{ $path_fonts }}/cormorantgaramond-bold-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
@font-face {
    font-family: 'poppins';
    src: url('{{ $path_fonts }}/poppins-regular-webfont.woff2') format('woff2'),
         url('{{ $path_fonts }}/poppins-regular-webfont.woff') format('woff'),
         url('{{ $path_fonts }}/poppins-regular-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
@font-face {
  font-family: 'poppins_light';
  src: url('{{ $path_fonts }}/poppins-light-webfont.woff2') format('woff2'),
  url('{{ $path_fonts }}/poppins-light-webfont.woff') format('woff'),
  url('{{ $path_fonts }}/poppins-light-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
@font-face {
  font-family: 'poppins_medium';
  src: url('{{ $path_fonts }}/poppins-medium-webfont.woff2') format('woff2'),
  url('{{ $path_fonts }}/poppins-medium-webfont.woff') format('woff'),
  url('{{ $path_fonts }}/poppins-medium-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
@font-face {
  font-family: 'poppins_semibold';
  src: url('{{ $path_fonts }}/poppins-semibold-webfont.woff2') format('woff2'),
  url('{{ $path_fonts }}/poppins-semibold-webfont.woff') format('woff'),
  url('{{ $path_fonts }}/poppins-semibold-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
@font-face {
  font-family: 'poppins_bold';
  src: url('{{ $path_fonts }}/poppins-bold-webfont.woff2') format('woff2'),
  url('{{ $path_fonts }}/poppins-bold-webfont.woff') format('woff'),
  url('{{ $path_fonts }}/poppins-bold-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'icon-social';
  src: url('{{ $path_fonts }}/icon-social/icon-social.eot?54164048');
  src: url('{{ $path_fonts }}/icon-social/icon-social.eot?54164048#iefix') format('embedded-opentype'),
  url('{{ $path_fonts }}/icon-social/icon-social.woff2?54164048') format('woff2'),
  url('{{ $path_fonts }}/icon-social/icon-social.woff?54164048') format('woff'),
  url('{{ $path_fonts }}/icon-social/icon-social.ttf?54164048') format('truetype'),
  url('{{ $path_fonts }}/icon-social/icon-social.svg?54164048#icon-social') format('svg');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'icon';
  src: url('{{ $path_fonts }}/icon/icon.eot?10479385');
  src: url('{{ $path_fonts }}/icon/icon.eot?10479385#iefix') format('embedded-opentype'),
  url('{{ $path_fonts }}/icon/icon.woff2?10479385') format('woff2'),
  url('{{ $path_fonts }}/icon/icon.woff?10479385') format('woff'),
  url('{{ $path_fonts }}/icon/icon.ttf?10479385') format('truetype'),
  url('{{ $path_fonts }}/icon/icon.svg?10479385#icon') format('svg');
  font-weight: normal;
  font-style: normal;
}

html.no-touchevents:not(.ie) {
  overflow: hidden;
  height: 100%;
}

html.no-touchevents:not(.ie) body {
  overflow: hidden;
  height: 100%;
}

/* preloader */
html:not(.ie) body.is-loading {
  position: fixed;
  overflow: hidden;
  top: 0;
  left: 0;
  width: 100%;
}
/*.global-container {
  opacity: 0;
}*/
.page-transition {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: #ffffff;
  z-index: 9998;

  font-size: 0;
  line-height: 0;

  display: flex;
  align-items: center;
  justify-content: center;
}
#preloader {
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -moz-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  -o-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}
#preloader .logo {
  opacity: 0;
  width: 200px;
  height: auto;
  max-width: 100%;
}

body.is-loaded .global-container {
  opacity: 1;
  visibility: visible;
}

body.is-loaded .site-preload {
  opacity: 0;
  visibility: hidden;
}
</style>
